#ifndef WEB_PAGE_H
#define WEB_PAGE_H

static const char WEB_PAGE[] =
    "<!DOCTYPE html>"
    "<html><head>"
    "<meta charset='UTF-8'>"
    "<meta name='viewport' content='width=device-width,initial-scale=1'>"
    "<title>ManCave Scroller</title>"
    "<style>"
    "*{box-sizing:border-box;margin:0;padding:0}"
    "body{font-family:Arial,sans-serif;max-width:480px;margin:0 auto;padding:20px;"
    "background:#1a1a2e;color:#e0e0e0}"
    "h1{text-align:center;color:#e94560;margin-bottom:20px;font-size:1.6em}"
    ".card{background:#16213e;border-radius:10px;padding:16px;margin-bottom:14px}"
    ".card h2{font-size:1em;color:#0f9b8e;margin-bottom:10px}"
    "label{display:block;font-size:.85em;margin-bottom:4px;color:#a0a0a0}"
    "input[type=text],input[type=password]{width:100%;padding:10px;border:1px solid #333;"
    "border-radius:6px;background:#0f3460;color:#e0e0e0;font-size:1em;margin-bottom:8px}"
    "input[type=color]{width:60px;height:36px;border:none;border-radius:6px;"
    "background:none;cursor:pointer;padding:0;margin-bottom:8px}"
    "input[type=range]{width:100%;margin-bottom:4px}"
    "button{width:100%;padding:10px;border:none;border-radius:6px;font-size:1em;"
    "cursor:pointer;background:#e94560;color:#fff;margin-top:6px}"
    "button:active{background:#c73651}"
    ".status{font-size:.85em;color:#888;text-align:center;margin-top:6px}"
    ".ok{color:#0f9b8e}"
    ".err{color:#e94560}"
    "#speedVal{font-weight:bold;color:#0f9b8e}"
    "</style>"
    "</head><body>"
    "<h1>ManCave Scroller</h1>"
    "<div id='st' class='status'>Loading...</div>"

    "<div class='card'><h2>Message</h2>"
    "<label>Scroll text:</label>"
    "<input type='text' id='msg' maxlength='200' placeholder='Enter message...'>"
    "<button onclick='setVal(\"text\",{text:g(\"msg\").value})'>Set Message</button>"
    "</div>"

    "<div class='card'><h2>Appearance</h2>"
    "<label>Text color:</label>"
    "<input type='color' id='color' value='#ff0000'>"
    "<button onclick='setColor()'>Set Color</button>"
    "<label>Scroll speed (1-10):</label>"
    "<input type='range' id='speed' min='1' max='10' value='5' "
    "oninput='g(\"speedVal\").textContent=this.value'>"
    "<span id='speedVal'>5</span>"
    "<button onclick='setVal(\"speed\",{speed:Number(g(\"speed\").value)})'>Set Speed</button>"
    "<label>Brightness (1-255):</label>"
    "<input type='range' id='bright' min='1' max='255' value='32' "
    "oninput='g(\"brightVal\").textContent=this.value'>"
    "<span id='brightVal'>32</span>"
    "<button onclick='setVal(\"brightness\",{brightness:Number(g(\"bright\").value)})'>Set Brightness</button>"
    "</div>"

    "<div class='card'><h2>WiFi Setup</h2>"
    "<label>SSID:</label>"
    "<input type='text' id='ssid' placeholder='WiFi network name'>"
    "<label>Password:</label>"
    "<input type='password' id='pass' placeholder='WiFi password'>"
    "<button onclick='setWifi()'>Connect to WiFi</button>"
    "</div>"

    "<script>"
    "function g(i){return document.getElementById(i)}"
    "function setVal(ep,d){"
    "fetch('/api/'+ep,{method:'POST',headers:{'Content-Type':'application/json'},"
    "body:JSON.stringify(d)}).then(r=>r.json()).then(j=>{"
    "g('st').className='status ok';g('st').textContent=j.status||'Updated!';"
    "}).catch(e=>{g('st').className='status err';g('st').textContent='Error: '+e})}"
    "function setColor(){"
    "var c=g('color').value;"
    "var r=parseInt(c.substr(1,2),16),gr=parseInt(c.substr(3,2),16),b=parseInt(c.substr(5,2),16);"
    "setVal('color',{r:r,g:gr,b:b})}"
    "function setWifi(){"
    "setVal('wifi',{ssid:g('ssid').value,password:g('pass').value})}"
    "function loadStatus(){"
    "fetch('/api/status').then(r=>r.json()).then(j=>{"
    "g('msg').value=j.text||'';"
    "g('speed').value=j.speed||5;g('speedVal').textContent=j.speed||5;"
    "g('bright').value=j.brightness||32;g('brightVal').textContent=j.brightness||32;"
    "if(j.color){var h='#'+('0'+j.color.r.toString(16)).slice(-2)"
    "+('0'+j.color.g.toString(16)).slice(-2)+('0'+j.color.b.toString(16)).slice(-2);"
    "g('color').value=h}"
    "if(j.wifi_ssid)g('ssid').value=j.wifi_ssid;"
    "g('st').className='status ok';"
    "g('st').textContent='WiFi: '+j.wifi_mode+' | IP: '+j.ip;"
    "}).catch(e=>{g('st').className='status err';g('st').textContent='Connection error'})}"
    "loadStatus();"
    "</script>"
    "</body></html>";

#endif
